[package]
name="artifactum-provider-ngc"
version.workspace=true
edition.workspace=true
rust-version.workspace=true
license.workspace=true
[dependencies]
artifactum-provider-command={path="../artifactum-provider-command"}
artifactum-provider-sdk={path="../artifactum-provider-sdk"}
tokio.workspace=true
[lints]
workspace=true
