[package]
name = "artifactum-resolver"
description = "Artifactum resolution, profiles, lazy acquisition and CAS orchestration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
artifactum-core = { path = "../artifactum-core" }
artifactum-store = { path = "../artifactum-store" }
artifactum-transport-http = { path = "../artifactum-transport-http" }
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
uuid.workspace = true
[lints]
workspace = true
