[package]
name = "artifactum-plugin-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
artifactum-plugin-protocol = { path = "../artifactum-plugin-protocol" }
uuid.workspace = true
serde.workspace = true
futures-util.workspace = true
daemonkit = { git = "https://github.com/akiselev/daemonkit", rev = "9f7dc96b343f8c892add1a0fee27ad6f73c15e57" }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
