[package]
name = "artifactum-provider-mlflow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "artifactum_provider_mlflow"

[[bin]]
name = "artifactum-provider-mlflow"
path = "src/main.rs"

[dependencies]
artifactum-core = { path = "../artifactum-core" }
artifactum-provider-command = { path = "../artifactum-provider-command" }
artifactum-plugin-protocol = { path = "../artifactum-plugin-protocol" }
async-trait.workspace = true
tokio.workspace = true
serde_json.workspace = true

[lints]
workspace = true
