[package]
name = "artifactum-remote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
artifactum-core = { path = "../artifactum-core" }
artifactum-store = { path = "../artifactum-store" }
async-trait.workspace = true
reqwest.workspace = true
tokio-util.workspace = true
sha2.workspace = true
hex.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
