[package]
name = "artifactum-provider-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
artifactum-resolver = { path = "../artifactum-resolver" }
artifactum-provider-sdk = { path = "../artifactum-provider-sdk" }
tokio.workspace = true
[lints]
workspace = true
