[package]
name = "artifactum-provider-azure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[lib]
name = "artifactum_provider_azure"
[[bin]]
name = "artifactum-provider-azure"
path = "src/main.rs"
[dependencies]
artifactum-provider-opendal = { path = "../artifactum-provider-opendal" }
artifactum-provider-sdk = { path = "../artifactum-provider-sdk" }
opendal = { version = "0.58", default-features = false, features = ["http-transport-reqwest","services-azblob"] }
tokio.workspace = true
[lints]
workspace = true
