use std::{collections::BTreeMap,path::Path};
use artifactum_core::{access_required,provider_error,AccessRequirement,AcquireContext,Acquisition,AcquisitionPlan,ArtifactPath,ArtifactProvider,ArtifactRequirement,Digest,ProviderCapabilities,ProviderDescriptor,ResolveContext,ResolvedFile,ResolvedRevision,Resolution};
use async_trait::async_trait;
use oci_client::{client::Client,manifest::OciDescriptor,secrets::RegistryAuth,Reference};

#[derive(Clone,Debug,Default)]pub struct OciProvider;
fn auth(profile:Option<&artifactum_core::ProviderProfile>)->RegistryAuth{let user_env=profile.and_then(|p|p.config.get("username_env")).map(String::as_str).unwrap_or("OCI_USERNAME");let pass_env=profile.and_then(|p|p.config.get("password_env")).map(String::as_str).unwrap_or("OCI_PASSWORD");match(std::env::var(user_env).ok(),std::env::var(pass_env).ok()){(Some(u),Some(p))=>RegistryAuth::Basic(u,p),_=>RegistryAuth::Anonymous}}
fn oci_error(e:impl std::fmt::Display)->artifactum_core::Error{let text=e.to_string();if text.to_ascii_lowercase().contains("unauthor")||text.contains("401")||text.contains("403"){access_required("oci",AccessRequirement::Authentication,text,None)}else{provider_error("oci",text)}}
#[async_trait]impl ArtifactProvider for OciProvider{
 fn descriptor(&self)->ProviderDescriptor{ProviderDescriptor{name:"oci".into(),version:env!("CARGO_PKG_VERSION").into(),schemes:vec!["oci".into()],capabilities:ProviderCapabilities{resolve:true,acquire:true,list:true,auth:true,..Default::default()},metadata:BTreeMap::from([("engine".into(),serde_json::Value::String("oci-client".into()))])}}
 async fn resolve(&self,r:&ArtifactRequirement,c:&ResolveContext)->artifactum_core::Result<Resolution>{if c.offline{return Err(provider_error("oci","cannot resolve while offline"));}let reference:Reference=r.reference.locator().parse().map_err(|e|provider_error("oci",e))?;let client=Client::new(Default::default());let(manifest,digest)=client.pull_image_manifest(&reference,&auth(c.profile.as_ref())).await.map_err(oci_error)?;let select=r.selection.compile()?;let mut files=Vec::new();for(index,layer)in manifest.layers.iter().enumerate(){let title=layer.annotations.as_ref().and_then(|a|a.get("org.opencontainers.image.title")).cloned().unwrap_or_else(||format!("layer-{index}-{}",layer.digest.replace(':',"-")));if !select.matches(&title){continue}let mut digests=artifactum_core::DigestSet::default();if let Ok(d)=layer.digest.parse::<Digest>(){digests.insert(d);}files.push(ResolvedFile{path:ArtifactPath::new(title)?,size:u64::try_from(layer.size).ok(),digests,media_type:Some(layer.media_type.clone()),source:serde_json::json!({"reference":reference.whole(),"descriptor":layer})});}Ok(Resolution{provider:"oci".into(),canonical_ref:format!("oci:{}",reference.whole()),revision:Some(ResolvedRevision{id:digest,requested:r.revision.clone()}),files,provider_state:serde_json::Value::Null,metadata:BTreeMap::new()})}
 async fn prepare_acquisition(&self,f:&ResolvedFile,_:&AcquireContext)->artifactum_core::Result<AcquisitionPlan>{Ok(AcquisitionPlan::ProviderManaged{state:f.source.clone()})}
 async fn acquire_managed(&self,f:&ResolvedFile,_:&AcquisitionPlan,d:&Path,c:&AcquireContext)->artifactum_core::Result<Acquisition>{if c.offline{return Err(provider_error("oci","cannot acquire while offline"));}let reference_text=f.source.get("reference").and_then(|v|v.as_str()).ok_or_else(||provider_error("oci","missing reference"))?;let reference:Reference=reference_text.parse().map_err(|e|provider_error("oci",e))?;let descriptor:OciDescriptor=serde_json::from_value(f.source.get("descriptor").cloned().ok_or_else(||provider_error("oci","missing layer descriptor"))?).map_err(|e|provider_error("oci",e))?;let client=Client::new(Default::default());client.store_auth_if_needed(reference.registry(),&auth(c.profile.as_ref())).await;let output=tokio::fs::File::create(d).await?;client.pull_blob(&reference,&descriptor,output).await.map_err(oci_error)?;let size=tokio::fs::metadata(d).await?.len();Ok(Acquisition{bytes_written:Some(size),metadata:Default::default()})}
}
pub fn provider()->OciProvider{OciProvider}
